---
# Site
baseurl: "" # TODO: Add this
title: "BETA"
enableRobotsTXT: true
googleAnalytics: ""
# Content
languageCode: "en-us"
defaultContentLanguage: "en"
# Formats
metaDataFormat: "yaml"
# -----------------------------
# DO NOT CHANGE BELOW THIS LINE
# -----------------------------
disableLiveReload: true
watch: false
menu:
  projects
